/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noyau_BridgeBot */

#ifndef _Included_noyau_BridgeBot
#define _Included_noyau_BridgeBot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     noyau_BridgeBot
 * Method:    bridgebotXjouer
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_BridgeBot_bridgebotXjouer
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     noyau_BridgeBot
 * Method:    bridgebotXinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_noyau_BridgeBot_bridgebotXinit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
