/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noyau_BridgeBot */

#ifndef _Included_noyau_BridgeBot
#define _Included_noyau_BridgeBot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     noyau_BridgeBot
 * Method:    bridgeXjouer
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_BridgeBot_bridgeXjouer
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     noyau_BridgeBot
 * Method:    bridgebotXinit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_noyau_BridgeBot_bridgebotXinit
  (JNIEnv *, jobject, jint);

/*
 * Class:     noyau_BridgeBot
 * Method:    bridgebotXlibererMemoire
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_noyau_BridgeBot_bridgebotXlibererMemoire
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
