/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noyau_Gotoonebot */

#ifndef _Included_noyau_Gotoonebot
#define _Included_noyau_Gotoonebot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     noyau_Gotoonebot
 * Method:    gotoonebotXjouer
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_Gotoonebot_gotoonebotXjouer
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     noyau_Gotoonebot
 * Method:    gotoonebotXinit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_noyau_Gotoonebot_gotoonebotXinit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
