/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noyau_PartieJNI */

#ifndef _Included_noyau_PartieJNI
#define _Included_noyau_PartieJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXinit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_noyau_PartieJNI_cretinhexXinit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXlargeurDamier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXlargeurDamier
  (JNIEnv *, jobject);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXaQuiDeJouer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXaQuiDeJouer
  (JNIEnv *, jobject);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXobtenirTour
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXobtenirTour
  (JNIEnv *, jobject);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXplacerPion
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_noyau_PartieJNI_cretinhexXplacerPion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXobtenirCase
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXobtenirCase
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXobtenirDamier
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_PartieJNI_cretinhexXobtenirDamier
  (JNIEnv *, jobject);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXobtenirDamierHisto
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_PartieJNI_cretinhexXobtenirDamierHisto
  (JNIEnv *, jobject, jint);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXquiGagne
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXquiGagne
  (JNIEnv *, jobject);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXsauvegarder
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noyau_PartieJNI_cretinhexXsauvegarder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXcharger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_noyau_PartieJNI_cretinhexXcharger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     noyau_PartieJNI
 * Method:    cretinhexXlibererMemoire
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_noyau_PartieJNI_cretinhexXlibererMemoire
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
