/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noyau_IA0 */

#ifndef _Included_noyau_IA0
#define _Included_noyau_IA0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     noyau_IA0
 * Method:    randombotXinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_noyau_IA0_randombotXinit
  (JNIEnv *, jobject);

/*
 * Class:     noyau_IA0
 * Method:    randombotXjouer
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_noyau_IA0_randombotXjouer
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
